### ISSUE TITLE
graphs/gen/batagelj_brandes.go should be renamed to erdos_renyi

### ISSUE THREAD

**Issue by jcao219** [gonum/graph#191]
I think it would be more recognizable. This looks like the Erdos-Renyi model. Thoughts?

**Comment by kortschak** [comment]
What are you proposing? `batagelj_brandes.go` contains a variety of graph generators, some of which are in that family, but are in a paper by Batagelj and Brandes - as noted in the file. Changing the name of the file would not make any of the functions more discoverable since the godoc links to the correct location.

**Comment by jcao219** [comment]
Oh, I didn't see the small world graph generator.

I guess the documentation for the two functions should just mention that
G(n,p) and G(n,m) are also known as Erdos-Renyi graphs.

**Comment by kortschak** [comment]
SGTM
